# РК №2

## Панов Герман Дмитриевич ИУ5-62Б

## Вариант 15

In [31]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [32]:
df = pd.read_csv('states_all_extended.csv')

In [33]:
df.head()

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,G08_HI_A_READING,G08_HI_A_MATHEMATICS,G08_AS_A_READING,G08_AS_A_MATHEMATICS,G08_AM_A_READING,G08_AM_A_MATHEMATICS,G08_HP_A_READING,G08_HP_A_MATHEMATICS,G08_TR_A_READING,G08_TR_A_MATHEMATICS
0,1992_ALABAMA,ALABAMA,1992,NaN,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1992_ALASKA,ALASKA,1992,NaN,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1992_ARIZONA,ARIZONA,1992,NaN,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1992_ARKANSAS,ARKANSAS,1992,NaN,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1992_CALIFORNIA,CALIFORNIA,1992,NaN,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1715 entries, 0 to 1714
Columns: 266 entries, PRIMARY_KEY to G08_TR_A_MATHEMATICS
dtypes: float64(263), int64(1), object(2)
memory usage: 3.5+ MB

In [35]:
df.dtypes

PRIMARY_KEY              object
STATE                    object
YEAR                      int64
ENROLL                  float64
TOTAL_REVENUE           float64
                         ...
G08_AM_A_MATHEMATICS    float64
G08_HP_A_READING        float64
G08_HP_A_MATHEMATICS    float64
G08_TR_A_READING        float64
G08_TR_A_MATHEMATICS    float64
Length: 266, dtype: object

In [36]:
df.isnull().sum()

PRIMARY_KEY                0
STATE                      0
YEAR                       0
ENROLL                   491
TOTAL_REVENUE            440
                        ...
G08_AM_A_MATHEMATICS    1655
G08_HP_A_READING        1701
G08_HP_A_MATHEMATICS    1702
G08_TR_A_READING        1574
G08_TR_A_MATHEMATICS    1570
Length: 266, dtype: int64

In [37]:
total_count = df.shape[0]

print('Всего строк: {}'.format(total_count))

Всего строк: 1715

### Обработка пропусков данных

In [40]:
# Обработка числовых пропусков

num_cols = []
num_cols_to_delete = []

for col in df.columns:
    temp_null_count = df[df[col].isnull()].shape[0]
    
    dt = str(df[col].dtype)
    
    if temp_null_count > 0 and (dt == 'float64' or dt == 'int64'):
        num_cols.append(col)
        
        temp_perc = round((temp_null_count / total_count) * 100.0, 2)
        
        if (temp_perc > 40):
            num_cols_to_delete.append(col)
        
        print('Колонка {}. Тип данных {}. Количество пустых значений {}, {}%.'.format(col, dt, temp_null_count, temp_perc))

Колонка ENROLL. Тип данных float64. Количество пустых значений 491, 28.63%.
Колонка TOTAL_REVENUE. Тип данных float64. Количество пустых значений 440, 25.66%.
Колонка FEDERAL_REVENUE. Тип данных float64. Количество пустых значений 440, 25.66%.
Колонка STATE_REVENUE. Тип данных float64. Количество пустых значений 440, 25.66%.
Колонка LOCAL_REVENUE. Тип данных float64. Количество пустых значений 440, 25.66%.
Колонка TOTAL_EXPENDITURE. Тип данных float64. Количество пустых значений 440, 25.66%.
Колонка INSTRUCTION_EXPENDITURE. Тип данных float64. Количество пустых значений 440, 25.66%.
Колонка SUPPORT_SERVICES_EXPENDITURE. Тип данных float64. Количество пустых значений 440, 25.66%.
Колонка OTHER_EXPENDITURE. Тип данных float64. Количество пустых значений 491, 28.63%.
Колонка CAPITAL_OUTLAY_EXPENDITURE. Тип данных float64. Количество пустых значений 440, 25.66%.
Колонка A_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка G01_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка G02_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка G03_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка G04_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка G05_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка G06_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка G07_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка G08_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка G09_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка G10_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка G11_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка G12_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка KG_A_A. Тип данных float64. Количество пустых значений 83, 4.84%.
Колонка PK_A_A. Тип данных float64. Количество пустых значений 173, 10.09%.
yes
Колонка G01-G08_A_A. Тип данных float64. Количество пустых значений 695, 40.52%.
Колонка G09-G12_A_A. Тип данных float64. Количество пустых значений 644, 37.55%.
yes
Колонка G01_AM_F. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G01_AM_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G01_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G01_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G01_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G01_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G01_HI_F. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G01_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G01_HP_F. Тип данных float64. Количество пустых значений 1351, 78.78%.
yes
Колонка G01_HP_M. Тип данных float64. Количество пустых значений 1352, 78.83%.
yes
Колонка G01_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G01_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G01_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G01_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G02_AM_F. Тип данных float64. Количество пустых значений 1309, 76.33%.
yes
Колонка G02_AM_M. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G02_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G02_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G02_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G02_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G02_HI_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G02_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G02_HP_F. Тип данных float64. Количество пустых значений 1351, 78.78%.
yes
Колонка G02_HP_M. Тип данных float64. Количество пустых значений 1351, 78.78%.
yes
Колонка G02_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G02_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G02_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G02_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G03_AM_F. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G03_AM_M. Тип данных float64. Количество пустых значений 1309, 76.33%.
yes
Колонка G03_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G03_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G03_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G03_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G03_HI_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G03_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G03_HP_F. Тип данных float64. Количество пустых значений 1352, 78.83%.
yes
Колонка G03_HP_M. Тип данных float64. Количество пустых значений 1349, 78.66%.
yes
Колонка G03_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G03_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G03_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G03_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G04_AM_F. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G04_AM_M. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G04_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G04_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G04_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G04_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G04_HI_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G04_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G04_HP_F. Тип данных float64. Количество пустых значений 1351, 78.78%.
yes
Колонка G04_HP_M. Тип данных float64. Количество пустых значений 1351, 78.78%.
yes
Колонка G04_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G04_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G04_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G04_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G05_AM_F. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G05_AM_M. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G05_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G05_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G05_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G05_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G05_HI_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G05_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G05_HP_F. Тип данных float64. Количество пустых значений 1352, 78.83%.
yes
Колонка G05_HP_M. Тип данных float64. Количество пустых значений 1349, 78.66%.
yes
Колонка G05_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G05_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G05_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G05_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G06_AM_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G06_AM_M. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G06_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G06_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G06_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G06_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G06_HI_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G06_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G06_HP_F. Тип данных float64. Количество пустых значений 1351, 78.78%.
yes
Колонка G06_HP_M. Тип данных float64. Количество пустых значений 1349, 78.66%.
yes
Колонка G06_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G06_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G06_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G06_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G07_AM_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G07_AM_M. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G07_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G07_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G07_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G07_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G07_HI_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G07_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G07_HP_F. Тип данных float64. Количество пустых значений 1350, 78.72%.
yes
Колонка G07_HP_M. Тип данных float64. Количество пустых значений 1352, 78.83%.
yes
Колонка G07_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G07_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G07_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G07_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G08_AM_F. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G08_AM_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G08_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G08_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G08_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G08_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G08_HI_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G08_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G08_HP_F. Тип данных float64. Количество пустых значений 1350, 78.72%.
yes
Колонка G08_HP_M. Тип данных float64. Количество пустых значений 1349, 78.66%.
yes
Колонка G08_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G08_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G08_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G08_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G09_AM_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G09_AM_M. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G09_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G09_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G09_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G09_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G09_HI_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G09_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G09_HP_F. Тип данных float64. Количество пустых значений 1352, 78.83%.
yes
Колонка G09_HP_M. Тип данных float64. Количество пустых значений 1351, 78.78%.
yes
Колонка G09_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G09_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G09_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G09_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G10_AM_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G10_AM_M. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G10_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G10_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G10_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G10_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G10_HI_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G10_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G10_HP_F. Тип данных float64. Количество пустых значений 1352, 78.83%.
yes
Колонка G10_HP_M. Тип данных float64. Количество пустых значений 1351, 78.78%.
yes
Колонка G10_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G10_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G10_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G10_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G11_AM_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G11_AM_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G11_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G11_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G11_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G11_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G11_HI_F. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка G11_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G11_HP_F. Тип данных float64. Количество пустых значений 1352, 78.83%.
yes
Колонка G11_HP_M. Тип данных float64. Количество пустых значений 1354, 78.95%.
yes
Колонка G11_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G11_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G11_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G11_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G12_AM_F. Тип данных float64. Количество пустых значений 1309, 76.33%.
yes
Колонка G12_AM_M. Тип данных float64. Количество пустых значений 1310, 76.38%.
yes
Колонка G12_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G12_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G12_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G12_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G12_HI_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G12_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G12_HP_F. Тип данных float64. Количество пустых значений 1352, 78.83%.
yes
Колонка G12_HP_M. Тип данных float64. Количество пустых значений 1352, 78.83%.
yes
Колонка G12_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G12_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка G12_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка G12_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка KG_AM_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка KG_AM_M. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка KG_AS_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка KG_AS_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка KG_BL_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка KG_BL_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка KG_HI_F. Тип данных float64. Количество пустых значений 1308, 76.27%.
yes
Колонка KG_HI_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка KG_HP_F. Тип данных float64. Количество пустых значений 1349, 78.66%.
yes
Колонка KG_HP_M. Тип данных float64. Количество пустых значений 1350, 78.72%.
yes
Колонка KG_TR_F. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка KG_TR_M. Тип данных float64. Количество пустых значений 1344, 78.37%.
yes
Колонка KG_WH_F. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка KG_WH_M. Тип данных float64. Количество пустых значений 1307, 76.21%.
yes
Колонка PK_AM_F. Тип данных float64. Количество пустых значений 1332, 77.67%.
yes
Колонка PK_AM_M. Тип данных float64. Количество пустых значений 1321, 77.03%.
yes
Колонка PK_AS_F. Тип данных float64. Количество пустых значений 1321, 77.03%.
yes
Колонка PK_AS_M. Тип данных float64. Количество пустых значений 1323, 77.14%.
yes
Колонка PK_BL_F. Тип данных float64. Количество пустых значений 1321, 77.03%.
yes
Колонка PK_BL_M. Тип данных float64. Количество пустых значений 1321, 77.03%.
yes
Колонка PK_HI_F. Тип данных float64. Количество пустых значений 1321, 77.03%.
yes
Колонка PK_HI_M. Тип данных float64. Количество пустых значений 1321, 77.03%.
yes
Колонка PK_HP_F. Тип данных float64. Количество пустых значений 1387, 80.87%.
yes
Колонка PK_HP_M. Тип данных float64. Количество пустых значений 1384, 80.7%.
yes
Колонка PK_TR_F. Тип данных float64. Количество пустых значений 1357, 79.13%.
yes
Колонка PK_TR_M. Тип данных float64. Количество пустых значений 1357, 79.13%.
yes
Колонка PK_WH_F. Тип данных float64. Количество пустых значений 1321, 77.03%.
yes
Колонка PK_WH_M. Тип данных float64. Количество пустых значений 1321, 77.03%.
yes
Колонка G04_A_A_READING. Тип данных float64. Количество пустых значений 1065, 62.1%.
yes
Колонка G04_A_A_MATHEMATICS. Тип данных float64. Количество пустых значений 1150, 67.06%.
yes
Колонка G04_A_M_READING. Тип данных float64. Количество пустых значений 1065, 62.1%.
yes
Колонка G04_A_M_MATHEMATICS. Тип данных float64. Количество пустых значений 1150, 67.06%.
yes
Колонка G04_A_F_READING. Тип данных float64. Количество пустых значений 1065, 62.1%.
yes
Колонка G04_A_F_MATHEMATICS. Тип данных float64. Количество пустых значений 1150, 67.06%.
yes
Колонка G04_WH_A_READING. Тип данных float64. Количество пустых значений 1450, 84.55%.
yes
Колонка G04_WH_A_MATHEMATICS. Тип данных float64. Количество пустых значений 1450, 84.55%.
yes
Колонка G04_BL_A_READING. Тип данных float64. Количество пустых значений 1489, 86.82%.
yes
Колонка G04_BL_A_MATHEMATICS. Тип данных float64. Количество пустых значений 1486, 86.65%.
yes
Колонка G04_HI_A_READING. Тип данных float64. Количество пустых значений 1465, 85.42%.
yes
Колонка G04_HI_A_MATHEMATICS. Тип данных float64. Количество пустых значений 1465, 85.42%.
yes
Колонка G04_AS_A_READING. Тип данных float64. Количество пустых значений 1551, 90.44%.
yes
Колонка G04_AS_A_MATHEMATICS. Тип данных float64. Количество пустых значений 1547, 90.2%.
yes
Колонка G04_AM_A_READING. Тип данных float64. Количество пустых значений 1651, 96.27%.
yes
Колонка G04_AM_A_MATHEMATICS. Тип данных float64. Количество пустых значений 1652, 96.33%.
yes
Колонка G04_HP_A_READING. Тип данных float64. Количество пустых значений 1699, 99.07%.
yes

In [23]:
df_num = df[num_cols]
df_num

,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,SUPPORT_SERVICES_EXPENDITURE,OTHER_EXPENDITURE,CAPITAL_OUTLAY_EXPENDITURE,...,G08_HI_A_READING,G08_HI_A_MATHEMATICS,G08_AS_A_READING,G08_AS_A_MATHEMATICS,G08_AM_A_READING,G08_AM_A_MATHEMATICS,G08_HP_A_READING,G08_HP_A_MATHEMATICS,G08_TR_A_READING,G08_TR_A_MATHEMATICS
0,NaN,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,735036.0,NaN,174053.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,350902.0,NaN,37451.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,1007732.0,NaN,609114.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,483488.0,NaN,145212.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,8520926.0,NaN,2044688.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,247.0,278.0,286.0,315.0,NaN,NaN,NaN,NaN,269.0,293.0
1711,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,248.0,267.0,285.0,315.0,237.0,259.0,NaN,NaN,263.0,292.0
1712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249.0,NaN
1713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,251.0,273.0,277.0,294.0,253.0,267.0,NaN,NaN,268.0,276.0
1714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,254.0,274.0,NaN,NaN,243.0,258.0,NaN,NaN,NaN,274.0

In [24]:
df_num_delete = df[num_cols_to_delete]
df_num_delete

,G01-G08_A_A,G01_AM_F,G01_AM_M,G01_AS_F,G01_AS_M,G01_BL_F,G01_BL_M,G01_HI_F,G01_HI_M,G01_HP_F,...,G08_HI_A_READING,G08_HI_A_MATHEMATICS,G08_AS_A_READING,G08_AS_A_MATHEMATICS,G08_AM_A_READING,G08_AM_A_MATHEMATICS,G08_HP_A_READING,G08_HP_A_MATHEMATICS,G08_TR_A_READING,G08_TR_A_MATHEMATICS
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,247.0,278.0,286.0,315.0,NaN,NaN,NaN,NaN,269.0,293.0
1711,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,248.0,267.0,285.0,315.0,237.0,259.0,NaN,NaN,263.0,292.0
1712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249.0,NaN
1713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,251.0,273.0,277.0,294.0,253.0,267.0,NaN,NaN,268.0,276.0
1714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,254.0,274.0,NaN,NaN,243.0,258.0,NaN,NaN,NaN,274.0

In [25]:
df = df.drop(num_cols_to_delete, axis=1)

In [26]:
df = df.dropna()

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1012 entries, 255 to 1274
Data columns (total 29 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PRIMARY_KEY                   1012 non-null   object
 1   STATE                         1012 non-null   object
 2   YEAR                          1012 non-null   int64
 3   ENROLL                        1012 non-null   float64
 4   TOTAL_REVENUE                 1012 non-null   float64
 5   FEDERAL_REVENUE               1012 non-null   float64
 6   STATE_REVENUE                 1012 non-null   float64
 7   LOCAL_REVENUE                 1012 non-null   float64
 8   TOTAL_EXPENDITURE             1012 non-null   float64
 9   INSTRUCTION_EXPENDITURE       1012 non-null   float64
 10  SUPPORT_SERVICES_EXPENDITURE  1012 non-null   float64
 11  OTHER_EXPENDITURE             1012 non-null   float64
 12  CAPITAL_OUTLAY_EXPENDITURE    1012 non-null   float64
 13  A_A_A                         1012 non-null   float64
 14  G01_A_A                       1012 non-null   float64
 15  G02_A_A                       1012 non-null   float64
 16  G03_A_A                       1012 non-null   float64
 17  G04_A_A                       1012 non-null   float64
 18  G05_A_A                       1012 non-null   float64
 19  G06_A_A                       1012 non-null   float64
 20  G07_A_A                       1012 non-null   float64
 21  G08_A_A                       1012 non-null   float64
 22  G09_A_A                       1012 non-null   float64
 23  G10_A_A                       1012 non-null   float64
 24  G11_A_A                       1012 non-null   float64
 25  G12_A_A                       1012 non-null   float64
 26  KG_A_A                        1012 non-null   float64
 27  PK_A_A                        1012 non-null   float64
 28  G09-G12_A_A                   1012 non-null   float64
dtypes: float64(26), int64(1), object(2)
memory usage: 237.2+ KB

In [30]:
# Обработка числовых пропусков

num_cols = []
num_cols_to_delete = []

for col in df.columns:
    temp_null_count = df[df[col].isnull()].shape[0]
    
    dt = str(df[col].dtype)
    
    if temp_null_count > 0 and (dt == 'float64' or dt == 'int64'):
        num_cols.append(col)
        
        temp_perc = round((temp_null_count / total_count) * 100.0, 2)
        
        if (temp_perc > 40):
            num_cols_to_delete.append(col)
        
        print('Колонка {}. Тип данных {}. Количество пустых значений {}, {}%.'.format(col, dt, temp_null_count, temp_perc))